### ISSUE TITLE
[TRACKING ISSUE] @jglovier's hack week goals

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/planning#8]
## App

**Product design**
- [ ] Flow for deployment
- [ ] Create overview screens for helpful info (charts, visualizations, etc)
- [ ] Dashboard concepts
  - [x] Sketch out concepts
  - [ ] Make design mocks

**Development**
- [ ] Improve seed data

**Cosmetic**
- [x] replace logo with new logo
- [ ] design new icons for UI
- [ ] replace octicons with SVG helpers

**Login screen**
- [x] add HospitalRun logo
- [x] add alert styling for forgotten passwords, wrong username, etc
- [ ] add forgot password link

**App navigation**
- [ ] fix settings nav
  - [ ] add appropriate links
  - [ ] make it so that clicking anywhere outside that nav will close it
- [ ] create minimized nav version for mobile
- [ ] add media queries for minimized nav to automatically work at smaller viewports (see GitLab for example)
- [ ] add media queries for smaller viewports for primary content panel nav, etc

**Forms and views**
- [ ] fix buttons on patient view
- [ ] improve seed data
- [ ] review feedback from user interviews

**Front end tasks**
- [x] Clean up CSS to pass linter
- [x] Merge jonrohan's PR
## Marketing site
- [ ] improve demo page
- [ ] create community page
- [ ] create docs
- [ ] add blog
- [ ] implement responsive framework for site
  - Gridism?
  - [Primer for marketing](http://github.github.io/primer-marketing/layout/)?
